# Generated by Django 3.0.5 on 2021-04-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subcomments',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='blog',
        ),
    ]
