# Generated by Django 3.1 on 2021-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
