# Generated by Django 3.1 on 2021-03-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210305_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profiles_followed',
            old_name='users',
            new_name='user',
        ),
    ]
